### ISSUE TITLE
could UTF8 string type be supported instead of ASCII as the default text encoding for CGNS?

### ISSUE THREAD

**Issue by qingfengxia** [CGNS/CGNS#684]
HDF5view show our written label/name are ASCII type, if modified to UTF8 type string using Python HDF5 API,  HDF5view is fine to show the non-ASCII string properly, but cgnsview, paraview does not.  

Not sure which part got messed up. CgnsVTKReader,  CgnsView?

**Comment by brtnfld** [comment]
It is most likely a cgnsview issue (i.e., tcl/tk usage issue). hdfview is java based, so UTF-8 is natively handled.

**Comment by qingfengxia** [comment]
`typedef char char_33[33];`     VTK IO seems transparents on UTF8, 

https://github.com/Kitware/VTK/blob/master/IO/CGNS/vtkCGNSReaderInternal.h

 it is likely paraview std::string ->QString translation has triggered some trouble, i will have a look.

**Comment by brtnfld** [comment]
How did you get utf-8 in CGNS? HDF5's default is ASCII, and the cgns library does not support changing it to utf-8.

**Comment by qingfengxia** [comment]
I have cgns, then I use H5py to modified label string to asian language , treating cgns as hdf5.  I see something weird in hdf5view,  if my locale is UTF8, asian string is still H5T_ASCII,  while if my locale encoding is GBK on windows,  string type is H5T_UTF8.

**Comment by qingfengxia** [comment]
`
import h5py

filename = "./HeatingCoil_modified.h5.cgns"
f = h5py.File(filename, "a")  #  mode = 'a'

# hdf5 use utf8 as the string encoding?
grp = f["Base"]["FluidZone"]["Flow Solution"]
newkey = "Pressure压力".encode(encoding = 'UTF-8')
if newkey in grp:
	del grp[newkey]

if True:
    newdata = grp["Pressure"]  # shallow copy link?    copy.copy is not allowed, not pickleable
    newdata.attrs["name"] = "Pressure压力"   # auto encoding with utf8.  
    print(newdata.attrs["name"])

    grp[newkey] = newdata  # create new data with utf8 as H5group name

f.close()
`

**Comment by MicK7** [comment]
The CGNS standard does not allow not ASCII names for nodes and it is not going to change soon.
Maybe you can try a CPEX to allow UTF-8 for strings stored in data container like DataArray_t. But for performance purpose UTF8 is not justified.

**Comment by brtnfld** [comment]
Closing since the CGNS standard does not support UTF-8. 

A CPEX would have to be submitted to handle UTF-8 officially, and it would have to address performance issues that could arise from UTF-8.
