### ISSUE TITLE
Problems compiling with MPI.

### ISSUE THREAD

**Issue by EnderWiggin14** [CGNS/CGNS#688]
Very simply, when `CGNS_ENABLE_TEST=ON` and `HDF5_NEED_MPI=ON` and run

`make -j4 2>&1 | tee cgns_make.out`

the build nearly finishes, but seemingly fails to find `mpi.mod`

The last few lines of the build output are below.

If I build with `CGNS_ENABLE_TEST=OFF`, the build succeeds, but I'm assuming that is more like sticking my head in the sand and pretending that it works when it doesn't.

How do I fix this?

```
[ 92%] Built target test_unstruc_quad
Scanning dependencies of target pcgns_ftest
[ 92%] Building Fortran object src/ptests/CMakeFiles/pcgns_ftest.dir/pcgns_ftest.F90.o
/home/admin2/CGNS/src/ptests/pcgns_ftest.F90:3:7:

    3 |   USE mpi
      |       1
Fatal Error: Cannot open module file ‘mpi.mod’ for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [src/ptests/CMakeFiles/pcgns_ftest.dir/build.make:75: src/ptests/CMakeFiles/pcgns_ftest.dir/pcgns_ftest.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3854: src/ptests/CMakeFiles/pcgns_ftest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Linking C executable thesis_benchmark
[ 94%] Linking C executable test_poly_unstructured
[ 94%] Built target thesis_benchmark
[ 94%] Built target test_poly_unstructured
[ 94%] Linking C executable test_general_readwrite
[ 94%] Built target test_general_readwrite
make: *** [Makefile:166: all] Error 2
```

**Comment by brtnfld** [comment]
Are you sure the Fortran mpi wrapper is being used? Can you "make VERBOSE=1"?

**Comment by EnderWiggin14** [comment]
I ran `make VERBOSE=1 2>&1 | tee cgns_make.out`.

The last number of lines are printed below. I have refrained from posting the entire verbose output of the the attempted compilation. If you would like me to post the entirety of it, I will.

Also I used the instructions in the [piclas installation guide](https://piclas.readthedocs.io/en/latest/userguide/installation.html) to install GCC, MPI, and HDF5.

```
[ 94%] Building Fortran object src/ptests/CMakeFiles/pcgns_ftest.dir/pcgns_ftest.F90.o
cd /home/admin2/CGNS/build/src/ptests && /home/admin2/gcc/12.2.0/bin/gfortran -DH5_BUILT_AS_STATIC_LIB -I/home/admin2/CGNS/build/src -I/home/admin2/CGNS/src -I/home/admin2/hdf5/1.12.1/include -fallow-argument-mismatch -DNO_CONCATENATION -O3 -DNDEBUG -O3 -c /home/admin2/CGNS/src/ptests/pcgns_ftest.F90 -o CMakeFiles/pcgns_ftest.dir/pcgns_ftest.F90.o
/home/admin2/CGNS/src/ptests/pcgns_ftest.F90:3:7:

    3 |   USE mpi
      |       1
Fatal Error: Cannot open module file ‘mpi.mod’ for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [src/ptests/CMakeFiles/pcgns_ftest.dir/build.make:75: src/ptests/CMakeFiles/pcgns_ftest.dir/pcgns_ftest.F90.o] Error 1
make[2]: Leaving directory '/home/admin2/CGNS/build'
make[1]: *** [CMakeFiles/Makefile2:3854: src/ptests/CMakeFiles/pcgns_ftest.dir/all] Error 2
make[1]: Leaving directory '/home/admin2/CGNS/build'
make: *** [Makefile:166: all] Error 2
```

**Comment by brtnfld** [comment]
Right, you are using just gfortran instead of mpif90, so it does not have the include path. Try exporting "FC" set to your mpif90 path and re-run CMake. You could also define for cmake:

-D CMAKE_Fortran_COMPILER:PATH="<your path>/mpif90"

**Comment by EnderWiggin14** [comment]
That worked. Thank you!

I used ccmake to set `CMAKE_Fortran_COMPILER=/usr/local/bin/mpif90`
