### ISSUE TITLE
CMake build fails with hdf5 1.14

### ISSUE THREAD

**Issue by MicK7** [CGNS/CGNS#692]
The issue is linked to https://github.com/HDFGroup/hdf5/issues/2422

**Error message:**

CMake Error in src/CMakeLists.txt:
  Imported target "hdf5::hdf5-shared" includes non-existent path

    "/home/conda/feedstock_root/build_artifacts/hdf5_1675775987664/work/src/H5FDsubfiling"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

The expected solution is on hdf5 side.

**Comment by MicK7** [comment]
Here is a simple handy fix:
`
# Workaround for leftover build directory paths in HDF5 installation
# https://github.com/HDFGroup/hdf5/issues/2422
sed -i.tmp 's/-I.*H5FDsubfiling//' \
    "$(which h5cc)" \
    "$(which h5c++)"
`

**Comment by brtnfld** [comment]
It is not fixed. I'll push for a fix for the 1.14.1 release.

**Comment by brtnfld** [comment]
@MicK7, was HDF5 built with CMake or Autotools? Was it a system-provided version of HDF5?

**Comment by MicK7** [comment]
HDF5 was built with autotools. HDF5 was not a system-provided version but it was part of a conda-forge feedstock so pretty standard. I don't think that spack system is affected since they use cmake but I need to check.
