### ISSUE TITLE
Format specifier macros for cgsize_t

### ISSUE THREAD

**Issue by jedbrown** [CGNS/CGNS#754]
HDF5 has the following definitions, which allow reading and formatting of type `hsize_t`.
```c
typedef uint64_t hsize_t;
typedef int64_t hssize_t;
#define PRIdHSIZE          PRId64
#define PRIiHSIZE          PRIi64
#define PRIoHSIZE          PRIo64
#define PRIuHSIZE          PRIu64
#define PRIxHSIZE          PRIx64
#define PRIXHSIZE          PRIX64
#define H5_SIZEOF_HSIZE_T  8
#define H5_SIZEOF_HSSIZE_T 8
```
CGNS has
```c
# if CG_BUILD_64BIT
#  define CG_SIZEOF_SIZE    64
#  define CG_SIZE_DATATYPE "I8"
   typedef CG_LONG_T cgsize_t;
# else
#  define CG_SIZEOF_SIZE    32
#  define CG_SIZE_DATATYPE "I4"
   typedef int cgsize_t;
# endif
```
Unfortunately, `CG_LONG_T` can take on different values depend on whether it's on Windows. It's also incompatible with `hssize_t` because `int64_t` usually maps to `long` (e.g., on x86-64) instead of `long long`. (I'm not saying they should be compatible, but HDF5 changed how they handle these types in https://github.com/HDFGroup/hdf5/pull/709 and I think that rationale also applies to CGNS.)

This is a minor headache for us in PETSc. Would you be amenable to a change similar to the HDF5 change above and adding `PRIdCGSIZE` (and others if someone wants them)?

Also, I'm assuming for now that 32-bit `cgsize_t` is important for some users. That makes it harder to package/distribute and requires libraries like ours to test both versions.

**Comment by brtnfld** [comment]
I don't see any issues with making similar changes; we already require C99.

**Comment by brtnfld** [comment]
This has been fixed and should be in the next release. Thanks for the report.
