### ISSUE TITLE
Potentially incorrect flag to specify HDF5 dir

### ISSUE THREAD

**Issue by prathamgit** [CGNS/CGNS#788]
In the line `   - The path to the HDF5 library should be specified with `CMAKE_PREFIX_PATH=$HDF_DIR` for linking with a specific HDF5 version.` in the README.md file, is the flag `CMAKE_PREFIX_PATH` correct?
According to src/SampleScripts/cmake.xl.mpich.sh it looks like the flag should be something similar to HDF5_LIBRARY_DIR.

**Comment by MicK7** [comment]
You are citing a 10 years old file as reference. Have you even taken the time to test yourself before raising an issue ?
Closing as spam.
